apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  namespace: django-todo
  labels:
    app: todo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      namespace: django-todo
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: royanu91/django-todo-app-image:v1
        ports:
        - containerPort: 5000

